"""
THIRTEENTH STUDY: Complete Parser Feature Showcase
===================================================

This study demonstrates EVERY parser feature implemented in the Codempose framework.

NEW FEATURES (Priority 3A + Unified Suffix Container):
1. Tuplets: [c d e]8 - bracket notation for rhythmic groupings
2. Ties: c4~ c4 - duration merging with pitch matching
3. Grace Notes: ~g16 - zero-duration ornamental notes
4. Articulations: c4(.) - staccato, tenuto, accent
5. Dynamics: d4(p) - piano, forte, mezzo-forte, etc.
6. Tracking: e4(themeA) - semantic labels for motifs
7. Combined Modifiers: f4(themeA, ., p) - all modifier types together

TRANSFORMATIONS (from transformations.py):
- Identity, Transpose, Invert, Retrograde, Augment, Diminish, Harmonize

COMPOSITION STRUCTURE:
- Theme A: Tuplets, ties, grace notes
- Theme B: Articulations, dynamics, tracking
- Theme C: Combined features (all modifiers)
- Intermezzo: Harmony sections (chords)
- Variations: Transformations applied to each theme

THREE-STATION WORKFLOW:
==========================================
Station 1: LilyPond Input - Composer's source of truth (THEME_A_LILY, etc.)
Station 2: TinyNotation Reference - Auto-generated for pitch resolution reference
Station 3: Blueprint Strings - Declarative score assembly with transformations

PROMOTION:
- Station 1 → Station 2: Automatic (reference only, not a stepping stone)
- Station 2 → Station 3: Manual promotion toggle (if needed for advanced control)
"""

# ============================================================================
# PROMOTION TOGGLE
# ============================================================================

PROMOTE_TO_PROGRAMMATIC = False


# ============================================================================
# IMPORTS
# ============================================================================

from typing import Dict, List
import copy
import music21

from lilypond_parser import parse_lilypond_to_data
from music_data import extract_data_from_part, data_to_part
from voice_documentation import register_and_document_voice
from composition_shorthand import build_score_from_assignments
from lily_converter import events_to_lily
from score_builder import build_score_from_blueprint
from transformations import (
    identity,
    transpose_part,
    invert_part,
    retrograde_part,
    augment_part,
    diminish_part,
    chordify_part
)


# ============================================================================
# STATION 1: ORIGINAL LILYPOND SNIPPETS (Input)
# ============================================================================
# 
# This is the composer's workspace. Define all musical material here as
# LilyPond notation snippets. These are your source of truth.
#
# Convention: Use descriptive names ending in _LILY
# Example: THEME_A_LILY, INTERMEZZO_LILY, VARIATION_LILY

# Theme A: Tuplets, Ties, Grace Notes
# Demonstrates rhythmic complexity with tuplets, sustained notes with ties,
# and ornamental grace notes
THEME_A_LILY = r"""
\relative c' {
    \time 4/4
    \key c \major
    \tempo 4=120
    c4 [d e f]8 e4~ e4 |
    ~g16 a2(p) [b c d]8 c4 |
    [e f g]8 f4 e2 d4 |
    ~c16 e2 e4 r1
}
"""

# # Theme B: Articulations, Dynamics, Tracking
# # Demonstrates musical expression with articulations (staccato, tenuto, accent),
# # dynamics (piano, forte, mezzo-forte), and semantic tracking labels
# THEME_B_LILY = r"""
# \relative c' {
#     \time 4/4
#     \key c \major
#     c4(., themeB) d4(-, p) e4(>, mf) f4(themeB) |
#     g4(., f) a4(-) b4(>, ff) c4(themeB, >) |
#     c4(p) b4(mp) a4(mf) g4(f) |
#     f4(., themeB) e4(-, p) d4 c4(themeB)
# }
# """

# # Theme C: Combined Features
# # Demonstrates ALL features working together: tuplets with modifiers,
# # tied notes with articulations and dynamics, grace notes with tracking
# THEME_C_LILY = r"""
# \relative c' {
#     \time 4/4
#     \key c \major
#     ~g16(f, themeC) [c4(., p) d4(-, mp) e4(>, mf)]8 |
#     f4(themeC, .)~ f4 [g4(p) a4(mf)]8 |
#     ~b16(ff) c4(themeC, >, ff)~ c4 b4(., p) |
#     a4(themeC) g4(-, mp) f4(.) e4(themeC, p)
# }
# """

# Intermezzo: Simple harmony for contrast
INTERMEZZO_LILY = r"""
\relative c, {
    \time 4/4
    \key c \major
    <c e g>2 <d f a>2 |
    <e g b>2 <f a c>2
}
"""


# ============================================================================
# STATION 2: TINYNOTATION EQUIVALENTS (Reference - Auto-generated)
# ============================================================================
#
# This section provides TinyNotation equivalents of the LilyPond snippets above.
# These are auto-generated during parsing and serve as a REFERENCE for pitch
# resolution verification. They are NOT a stepping stone in the workflow.
#
# Purpose: Verify that the parser correctly resolved relative octaves
# Usage: Compare with parser output to debug pitch issues

# Auto-generated by parser - populated during build
THEME_A_TINY = "tinynotation: 4/4 c4 d8 e8 f8 e4~ e4 g16grace a2 b8 c8 d8 c4~ c4 e8 f8 g8 f4 e2 d4 c16grace e2~ e4 r2"
# THEME_B_TINY = "tinynotation: 4/4 c4. d4- e4> f4 g4. a4- b4> c4> c4 b4 a4 g4 f4. e4- d4 c4"
# THEME_C_TINY = "tinynotation: 4/4 g16grace c4. d4- e4> f4.~ f4 g4 a4 b16grace c4>~ c4 b4. a4 g4- f4. e4"
INTERMEZZO_TINY = "tinynotation: 4/4 <c e g>2 <d f a>2 <e g b>2 <f a c>2"


# ============================================================================
# STATION 3: BLUEPRINT STRINGS (Framework - Declarative Assembly)
# ============================================================================
#
# Blueprint String Framework: Composer-centric shorthand for multi-stave scores.
# Uses intuitive delimiters that map to musical concepts.
#
# DELIMITER SYNTAX:
#   ; (semicolon)  → Separates SECTIONS (like double barlines)
#   & (ampersand)   → Separates STAVES (vertical stacking)
#   | (pipe)        → Concatenates SNIPPETS ("then" operator)
#   , (comma)       → Separates VOICES in multi-voice staves
#
# READING AS A TABLE:
#   Each line before ; is a section (row)
#   & separates staves (columns)
#   | means "play this, then that"
#   'r' auto-generates rests matching active staves
#
# EXAMPLE:
#   VOICE_STAVE_DEF = "UpperStaff & LowerStaff"
#   
#   VOICE_STAVE_DATA = """
#       INTRO | THEME  & r;           # Upper: INTRO then THEME; Lower: rests
#       r              & INTERMEZZO;  # Upper: rests; Lower: INTERMEZZO
#       VARIATION      & HARMONY      # Both active
#   """
#
# BENEFITS:
#   ✓ 77% less code vs manual assembly
#   ✓ Visual clarity (reads like a score)
#   ✓ Easy modifications (reorder sections by moving lines)
#   ✓ Automatic rest generation
#   ✓ Scales to any number of staves
#
# IMPLEMENTATION NOTE:
#   Blueprint strings are defined inside build_score_data() at lines 327-365
#   where they have access to parsed events. See Station 3 below.


# ============================================================================
# STATION 3: PROGRAMMATIC ASSEMBLY (Optional - Full Control)
# ============================================================================

def build_score_data() -> Dict[str, Dict]:
    """
    Build complete feature showcase - programmatic version.
    
    This function generates the entire score by:
    1. Parsing all three themes from LilyPond
    2. Generating transformations for each theme
    3. Assembling everything into a single MainLine
    4. Documenting every section with voice tracking metadata
    
    Returns:
        Dictionary with 'metadata' and 'parts' keys
    """
    print("\n" + "="*70)
    print("THIRTEENTH STUDY: Complete Parser Feature Showcase")
    print("="*70)
    
    # ========================================================================
    # PARSE ALL THEMES
    # ========================================================================
    
    print("\n[Parsing themes...]")
    
    # Theme A: Tuplets, Ties, Grace Notes
    parsed_a = parse_lilypond_to_data(THEME_A_LILY, part_name='ThemeA')
    theme_a_events = parsed_a.get('parts', {}).get('ThemeA', [])
    theme_a_part = data_to_part(theme_a_events, parsed_a.get('metadata', {}))
    print(f"✓ Theme A: {len(theme_a_events)} events (tuplets, ties, grace notes)")
    
    # # Theme B: Articulations, Dynamics, Tracking
    # parsed_b = parse_lilypond_to_data(THEME_B_LILY, part_name='ThemeB')
    # theme_b_events = parsed_b.get('parts', {}).get('ThemeB', [])
    # theme_b_part = data_to_part(theme_b_events, parsed_b.get('metadata', {}))
    # print(f"✓ Theme B: {len(theme_b_events)} events (articulations, dynamics, tracking)")
    
    # # Theme C: Combined Features
    # parsed_c = parse_lilypond_to_data(THEME_C_LILY, part_name='ThemeC')
    # theme_c_events = parsed_c.get('parts', {}).get('ThemeC', [])
    # theme_c_part = data_to_part(theme_c_events, parsed_c.get('metadata', {}))
    # print(f"✓ Theme C: {len(theme_c_events)} events (combined features)")
    
    # Intermezzo: Harmony sections
    print(f"   🔍 DEBUG: INTERMEZZO_LILY input:")
    print(f"      {repr(INTERMEZZO_LILY[:100])}")
    parsed_intermezzo = parse_lilypond_to_data(INTERMEZZO_LILY, part_name='Intermezzo')
    intermezzo_events = parsed_intermezzo.get('parts', {}).get('Intermezzo', [])
    intermezzo_part = data_to_part(intermezzo_events, parsed_intermezzo.get('metadata', {}))
    print(f"✓ Intermezzo: {len(intermezzo_events)} events (harmony)")
    if len(intermezzo_events) == 0:
        print(f"   ⚠️  WARNING: Intermezzo parsed to 0 events!")
        print(f"   📋 Raw parse result keys: {list(parsed_intermezzo.keys())}")
        print(f"   📋 Available parts: {list(parsed_intermezzo.get('parts', {}).keys())}")
        if intermezzo_events:
            print(f"   📋 First event: {intermezzo_events[0]}")
    
    # ========================================================================
    # GENERATE TRANSFORMATIONS
    # ========================================================================
    
    print("\n[Generating transformations...]")
    
    # Theme A variations
    theme_a_transposed = extract_data_from_part(transpose_part(theme_a_part, 'P5'))
    theme_a_inverted = extract_data_from_part(invert_part(theme_a_part, 'C4'))
    # Harmonize and transpose down an octave so chords are in better range
    theme_a_harmony_part = chordify_part(theme_a_part)
    theme_a_harmony_part = transpose_part(theme_a_harmony_part, 'P-8')  # Down one octave
    theme_a_harmony = extract_data_from_part(theme_a_harmony_part)
    print(f"✓ Theme A: Transposed (+P5), Inverted (C4), Harmonized")
    
    # ========================================================================
    # CONVERT VARIATIONS TO LILYPOND SNIPPETS
    # ========================================================================
    
    print("\n[Converting variations to LilyPond snippets...]")
    
    # Create basic metadata for snippet conversion
    snippet_metadata = {
        'time_signature': '4/4',
        'key_signature': {'tonic': 'c', 'mode': 'major'}
    }
    
    # Convert each variation back to LilyPond notation
    generated_snippets = {}
    
    generated_snippets['THEME_A_TRANSPOSED'] = events_to_lily(theme_a_transposed, snippet_metadata)
    print(f"✓ Generated THEME_A_TRANSPOSED_LILY snippet")
    
    generated_snippets['THEME_A_INVERTED'] = events_to_lily(theme_a_inverted, snippet_metadata)
    print(f"✓ Generated THEME_A_INVERTED_LILY snippet")
    
    generated_snippets['THEME_A_HARMONIZED'] = events_to_lily(theme_a_harmony, snippet_metadata)
    print(f"✓ Generated THEME_A_HARMONIZED_LILY snippet")
    
    # # Theme B variations
    # theme_b_retrograde = extract_data_from_part(retrograde_part(theme_b_part))
    # theme_b_augmented = extract_data_from_part(augment_part(theme_b_part, 2.0))
    # theme_b_harmony = extract_data_from_part(chordify_part(theme_b_part))
    # print(f"✓ Theme B: Retrograde, Augmented (×2), Harmonized")
    
    # # Theme C variations
    # theme_c_diminished = extract_data_from_part(diminish_part(theme_c_part, 2.0))
    # theme_c_octave_up = extract_data_from_part(transpose_part(theme_c_part, 'P8'))
    # theme_c_harmony = extract_data_from_part(chordify_part(theme_c_part))
    # print(f"✓ Theme C: Diminished (×0.5), Octave Up (+P8), Harmonized")
    
    # ========================================================================
    # ASSEMBLE TWO-STAVE STRUCTURE WITH BLUEPRINT STRINGS (STATION 3)
    # ========================================================================
    
    print("\n[Assembling two-stave structure with Blueprint Strings...]")
    
    # -------------------------------------------------------------------------
    # BLUEPRINT STRING FRAMEWORK
    # -------------------------------------------------------------------------
    # This replaces 130+ lines of manual assembly with 30 lines of declarative
    # blueprint strings. The framework uses musically intuitive delimiters:
    #
    #   ; = Section separator (like double barlines)
    #   & = Staff separator (vertical stacking)
    #   | = Snippet concatenator (horizontal "then")
    #   , = Voice separator (multi-voice staves)
    #
    # Benefits:
    #   - 77% code reduction
    #   - Reads like a score table
    #   - Easy to reorder sections
    #   - Automatic rest generation
    # -------------------------------------------------------------------------
    
    # STEP 1: Define the layout (which staves exist)
    VOICE_STAVE_DEF = "UpperStaff & LowerStaff"
    
    # STEP 2: Define the musical content (section by section)
    # Read this like a table where each line is a section:
    #   - Before &: What UpperStaff plays
    #   - After &: What LowerStaff plays
    #   - 'r' means auto-generate rests matching the other staff's duration
    #   - ';' marks the end of a section
    VOICE_STAVE_DATA = """
        THEME_A & r;
        r & INTERMEZZO;
        THEME_A_TRANSPOSED & r;
        r & INTERMEZZO;
        THEME_A_INVERTED & r;
        r & INTERMEZZO;
        THEME_A_HARMONIZED & r
    """
    
    # STEP 3: Define the snippet library (the musical material)
    # Each key corresponds to a snippet name used in VOICE_STAVE_DATA
    SNIPPETS = {
        'THEME_A': theme_a_events,
        'THEME_A_TRANSPOSED': theme_a_transposed,
        'THEME_A_INVERTED': theme_a_inverted,
        'THEME_A_HARMONIZED': theme_a_harmony,
        'INTERMEZZO': intermezzo_events,
    }
    
    # STEP 4: Build the score using blueprint framework
    # The framework:
    #   - Parses the layout and content strings
    #   - Assembles events from the snippet library
    #   - Generates rests where 'r' is specified
    #   - Adds section barlines automatically
    basic_metadata = {
        'time_signature': '4/4',
        'key_signature': {'tonic': 'c', 'mode': 'major'}
    }
    
    score_result = build_score_from_blueprint(
        VOICE_STAVE_DEF,
        VOICE_STAVE_DATA,
        SNIPPETS,
        basic_metadata
    )
    
    # STEP 5: Extract the assembled parts for further processing
    upper_staff = score_result['parts']['UpperStaff']
    lower_staff = score_result['parts']['LowerStaff']
    
    # ========================================================================
    # FEATURE ANALYSIS
    # ========================================================================
    
    print("\n[Feature analysis...]")
    
    # Count features in Theme A
    tuplet_count = sum(1 for e in theme_a_events if e.get('type') == 'tuplet')
    grace_count = sum(1 for e in theme_a_events if e.get('is_grace', False))
    tied_count = sum(1 for e in theme_a_events if '~' in e.get('original_token', ''))
    print(f"✓ Theme A features:")
    print(f"   - Tuplets: {tuplet_count}")
    print(f"   - Grace notes: {grace_count}")
    print(f"   - Tied notes: {tied_count}")
    
    # # Count features in Theme B
    # artic_count = sum(1 for e in theme_b_events if e.get('articulations'))
    # dyn_count = sum(1 for e in theme_b_events if e.get('dynamics'))
    # track_count = sum(1 for e in theme_b_events if e.get('tracker'))
    # print(f"✓ Theme B features:")
    # print(f"   - Articulations: {artic_count}")
    # print(f"   - Dynamics: {dyn_count}")
    # print(f"   - Tracking labels: {track_count}")
    
    # # Count features in Theme C
    # combined_count = sum(1 for e in theme_c_events 
    #                     if e.get('articulations') and e.get('dynamics') and e.get('tracker'))
    # print(f"✓ Theme C features:")
    # print(f"   - Combined modifiers: {combined_count}")
    
    # ========================================================================
    # VOICE TRACKING METADATA
    # ========================================================================
    
    voice_tracking = {
        '01_ThemeA_Original': {
            'source': 'THEME_A_LILY',
            'transformation': 'identity',
            'description': 'Original theme with tuplets, ties, grace notes',
            'features': ['tuplets', 'ties', 'grace_notes'],
            'events': len(theme_a_events),
        },
        '02_Intermezzo_1': {
            'source': 'INTERMEZZO_LILY',
            'transformation': 'identity',
            'description': 'Harmonic interlude (chords)',
            'features': ['harmony'],
            'events': len(intermezzo_events),
        },
        '03_ThemeA_Transposed': {
            'source': 'THEME_A_LILY',
            'transformation': 'transpose(P5)',
            'description': 'Theme A transposed up perfect fifth',
            'features': ['tuplets', 'ties', 'grace_notes', 'transposition'],
            'events': len(theme_a_transposed),
        },
        '04_Intermezzo_2': {
            'source': 'INTERMEZZO_LILY',
            'transformation': 'identity',
            'description': 'Harmonic interlude (chords)',
            'features': ['harmony'],
            'events': len(intermezzo_events),
        },
        '05_ThemeA_Inverted': {
            'source': 'THEME_A_LILY',
            'transformation': 'invert(center=C4)',
            'description': 'Theme A melodically inverted around C4',
            'features': ['tuplets', 'ties', 'grace_notes', 'inversion'],
            'events': len(theme_a_inverted),
        },
        '06_Intermezzo_3': {
            'source': 'INTERMEZZO_LILY',
            'transformation': 'identity',
            'description': 'Harmonic interlude (chords)',
            'features': ['harmony'],
            'events': len(intermezzo_events),
        },
        # '07_ThemeB_Original': {
        #     'source': 'THEME_B_LILY',
        #     'transformation': 'identity',
        #     'description': 'Original theme with articulations, dynamics, tracking',
        #     'features': ['articulations', 'dynamics', 'tracking'],
        #     'events': len(theme_b_events),
        # },
        # '08_Intermezzo_4': {
        #     'source': 'INTERMEZZO_LILY',
        #     'transformation': 'identity',
        #     'description': 'Harmonic interlude (chords)',
        #     'features': ['harmony'],
        #     'events': len(intermezzo_events),
        # },
        # '09_ThemeB_Retrograde': {
        #     'source': 'THEME_B_LILY',
        #     'transformation': 'retrograde()',
        #     'description': 'Theme B in reverse order',
        #     'features': ['articulations', 'dynamics', 'tracking', 'retrograde'],
        #     'events': len(theme_b_retrograde),
        # },
        # '10_Intermezzo_5': {
        #     'source': 'INTERMEZZO_LILY',
        #     'transformation': 'identity',
        #     'description': 'Harmonic interlude (chords)',
        #     'features': ['harmony'],
        #     'events': len(intermezzo_events),
        # },
        # '11_ThemeB_Augmented': {
        #     'source': 'THEME_B_LILY',
        #     'transformation': 'augment(factor=2.0)',
        #     'description': 'Theme B with doubled durations',
        #     'features': ['articulations', 'dynamics', 'tracking', 'augmentation'],
        #     'events': len(theme_b_augmented),
        # },
        # '12_Intermezzo_6': {
        #     'source': 'INTERMEZZO_LILY',
        #     'transformation': 'identity',
        #     'description': 'Harmonic interlude (chords)',
        #     'features': ['harmony'],
        #     'events': len(intermezzo_events),
        # },
        # '13_ThemeC_Original': {
        #     'source': 'THEME_C_LILY',
        #     'transformation': 'identity',
        #     'description': 'Original theme with ALL features combined',
        #     'features': ['tuplets', 'ties', 'grace_notes', 'articulations', 'dynamics', 'tracking'],
        #     'events': len(theme_c_events),
        # },
        # '14_Intermezzo_7': {
        #     'source': 'INTERMEZZO_LILY',
        #     'transformation': 'identity',
        #     'description': 'Harmonic interlude (chords)',
        #     'features': ['harmony'],
        #     'events': len(intermezzo_events),
        # },
        # '15_ThemeC_Diminished': {
        #     'source': 'THEME_C_LILY',
        #     'transformation': 'diminish(factor=2.0)',
        #     'description': 'Theme C with halved durations',
        #     'features': ['tuplets', 'ties', 'grace_notes', 'articulations', 'dynamics', 'tracking', 'diminution'],
        #     'events': len(theme_c_diminished),
        # },
        # '16_Intermezzo_8': {
        #     'source': 'INTERMEZZO_LILY',
        #     'transformation': 'identity',
        #     'description': 'Harmonic interlude (chords)',
        #     'features': ['harmony'],
        #     'events': len(intermezzo_events),
        # },
        # '17_ThemeC_OctaveUp': {
        #     'source': 'THEME_C_LILY',
        #     'transformation': 'transpose(P8)',
        #     'description': 'Theme C transposed up one octave',
        #     'features': ['tuplets', 'ties', 'grace_notes', 'articulations', 'dynamics', 'tracking', 'transposition'],
        #     'events': len(theme_c_octave_up),
        # },
        # '18_Intermezzo_9': {
        #     'source': 'INTERMEZZO_LILY',
        #     'transformation': 'identity',
        #     'description': 'Harmonic interlude (chords)',
        #     'features': ['harmony'],
        #     'events': len(intermezzo_events),
        # },
        '19_Finale_A': {
            'source': 'THEME_A_LILY',
            'transformation': 'chordify()',
            'description': 'Theme A harmonized (triadic chords)',
            'features': ['harmony', 'chordification'],
            'events': len(theme_a_harmony),
        },
        # '20_Finale_B': {
        #     'source': 'THEME_B_LILY',
        #     'transformation': 'chordify()',
        #     'description': 'Theme B harmonized (triadic chords)',
        #     'features': ['harmony', 'chordification'],
        #     'events': len(theme_b_harmony),
        # },
        # '21_Finale_C': {
        #     'source': 'THEME_C_LILY',
        #     'transformation': 'chordify()',
        #     'description': 'Theme C harmonized (triadic chords)',
        #     'features': ['harmony', 'chordification'],
        #     'events': len(theme_c_harmony),
        # },
    }
    
    # ========================================================================
    # RETURN COMPLETE DATA STRUCTURE
    # ========================================================================
    
    return {
        'metadata': {
            'title': 'Thirteenth Study: Theme A and Intermezzo Focus',
            'composer': 'Codempose Framework',
            'time_signature': '4/4',
            'tempo': '120',
            'key_signature': 'C major',
            'original_snippets': {
                'THEME_A': THEME_A_LILY,
                # 'THEME_B': THEME_B_LILY,
                # 'THEME_C': THEME_C_LILY,
                'INTERMEZZO': INTERMEZZO_LILY,
            },
            'generated_snippets': generated_snippets,  # Generated LilyPond from transformations
            'voice_tracking': voice_tracking,
            'feature_summary': {
                'tuplets': f'{tuplet_count} in Theme A',
                'grace_notes': f'{grace_count} in Theme A',
                'ties': f'{tied_count} in Theme A',
                # 'articulations': f'{artic_count} in Theme B',
                # 'dynamics': f'{dyn_count} in Theme B',
                # 'tracking': f'{track_count} in Theme B',
                # 'combined_modifiers': f'{combined_count} in Theme C',
                'transformations': '3 variations (transpose, invert, harmonize)',
            },
            'staff_info': {
                'UpperStaff': {
                    'clef': 'treble',
                    'role': 'melody',
                },
                'LowerStaff': {
                    'clef': 'bass',
                    'role': 'harmony',
                },
            },
        },
        'parts': {
            'UpperStaff': upper_staff,
            'LowerStaff': lower_staff,
        }
    }


# ============================================================================
# MAIN EXECUTION
# ============================================================================

if __name__ == '__main__':
    from project_template import run_pipeline_from_file
    
    print("\n" + "="*70)
    print("THIRTEENTH STUDY: Complete Parser Feature Showcase")
    print("="*70)
    print("\n💡 This study demonstrates EVERY parser feature:")
    print("\n📌 NEW FEATURES (Priority 3A + Unified Suffix Container):")
    print("   1. Tuplets: [c d e]8 - rhythmic groupings in brackets")
    print("   2. Ties: c4~ c4 - duration merging with pitch matching")
    print("   3. Grace Notes: ~g16 - zero-duration ornamental notes")
    print("   4. Articulations: c4(.) - staccato, tenuto, accent")
    print("   5. Dynamics: d4(p) - piano, forte, mezzo-forte, etc.")
    print("   6. Tracking: e4(themeA) - semantic labels for motifs")
    print("   7. Combined: f4(themeA, ., p) - all modifiers together")
    print("\n🔧 TRANSFORMATIONS (from transformations.py):")
    print("   - Identity, Transpose, Invert, Retrograde")
    print("   - Augment, Diminish, Octave shifts, Harmonize")
    print("\n🎼 STRUCTURE:")
    print("   - Theme A: Tuplets + Ties + Grace Notes")
    print("   - Theme B: Articulations + Dynamics + Tracking")
    print("   - Theme C: ALL features combined")
    print("   - Intermezzos: Harmony sections between themes")
    print("   - Finale: All themes harmonized")
    print("\n📊 OUTPUT:")
    print("   - LilyPond (.ly) - human-readable notation")
    print("   - MIDI (.midi) - audio playback")
    print("   - MusicXML (.musicxml) - import to MuseScore/Finale")
    print("   - Voice documentation with feature analysis")
    print("\n" + "="*70 + "\n")
    
    # Run the standard pipeline
    run_pipeline_from_file(__file__)
