#!/usr/bin/env bash
# Fix devcontainer helper - manually fix common devcontainer issues
# This script can be run anytime to:
# - Restore the /Codempose prompt
# - Restart the HTTP server on port 8888
# - Regenerate outputs
# - Make ports public/accessible

set -euo pipefail

LOGFILE=".devcontainer/fix_devcontainer.log"
PIDFILE=".devcontainer/devcontainer-server.pid"

echo "Fix devcontainer helper started: $(date)" | tee -a "$LOGFILE"

# Step 1: Install canonical prompt
echo "1) Install canonical prompt to \$HOME/.bash_prompt_choice" | tee -a "$LOGFILE"
if [ -f ".devcontainer/bash_prompt_choice" ]; then
  cp .devcontainer/bash_prompt_choice "$HOME/.bash_prompt_choice" || true
  chown $(id -u):$(id -g) "$HOME/.bash_prompt_choice" || true
  echo "Copied prompt choice to $HOME/.bash_prompt_choice" | tee -a "$LOGFILE"
fi

# Step 2: Ensure ~/.bashrc sources the prompt
echo "2) Ensure ~/.bashrc sources the prompt choice" | tee -a "$LOGFILE"
PROMPT_GREP='bash_prompt_choice'
if [ -f "$HOME/.bashrc" ]; then
  if ! grep -Fq "$PROMPT_GREP" "$HOME/.bashrc" 2>/dev/null; then
    printf "\n# Source project canonical prompt (installed by fix helper)\nif [ -f \"\$HOME/.bash_prompt_choice\" ]; then\n  . \"\$HOME/.bash_prompt_choice\"\nfi\n" >> "$HOME/.bashrc" || true
    echo "Appended prompt sourcing to ~/.bashrc" | tee -a "$LOGFILE"
  else
    echo "~/.bashrc already sources bash_prompt_choice" | tee -a "$LOGFILE"
  fi
else
  printf "# ~/.bashrc generated by fix helper\nif [ -f \"\$HOME/.bash_prompt_choice\" ]; then\n  . \"\$HOME/.bash_prompt_choice\"\nfi\n" > "$HOME/.bashrc" || true
  echo "Created ~/.bashrc with prompt sourcing" | tee -a "$LOGFILE"
fi

# Step 3: Make devcontainer-start.sh executable
echo "3) Ensure .devcontainer/devcontainer-start.sh is executable" | tee -a "$LOGFILE"
if [ -f ".devcontainer/devcontainer-start.sh" ]; then
  chmod +x .devcontainer/devcontainer-start.sh
  echo "Marked .devcontainer/devcontainer-start.sh executable" | tee -a "$LOGFILE"
fi

# Step 4: Ensure outputs directory exists
echo "4) Ensure outputs/ exists" | tee -a "$LOGFILE"
mkdir -p outputs

# Step 5: Regenerate project outputs (optional - ask user)
echo ""
echo "Do you want to regenerate outputs? (y/N)"
read -r response
if [[ "$response" =~ ^[Yy]$ ]]; then
  echo "5) Run project generation (project_template.py) and capture output" | tee -a "$LOGFILE"
  if python3 project_template.py >> "$LOGFILE" 2>&1; then
    echo "✅ Generation completed successfully." | tee -a "$LOGFILE"
  else
    echo "⚠️  Generation failed; see $LOGFILE for details." | tee -a "$LOGFILE"
  fi
else
  echo "5) Skipped project generation" | tee -a "$LOGFILE"
fi

# Step 6: Restart HTTP server on port 8888
echo ""
echo "6) Restart HTTP server on port 8888" | tee -a "$LOGFILE"

# Stop existing server if running
if [ -f "$PIDFILE" ]; then
  OLDPID=$(cat "$PIDFILE" 2>/dev/null || true)
  if [ -n "$OLDPID" ] && ps -p "$OLDPID" > /dev/null 2>&1; then
    echo "Stopping previous server (PID $OLDPID)..." | tee -a "$LOGFILE"
    kill "$OLDPID" || true
    sleep 1
  fi
fi

# Also kill any other python http.server on 8888
pkill -f "http.server 8888" 2>/dev/null || true
sleep 0.5

# Start new server
echo "Starting HTTP server on 0.0.0.0:8888 (serving outputs/)..." | tee -a "$LOGFILE"
nohup python3 -m http.server 8888 --bind 0.0.0.0 --directory outputs >> "$LOGFILE" 2>&1 &
echo $! > "$PIDFILE"
NEW_PID=$(cat "$PIDFILE")
echo "✅ HTTP server started (PID $NEW_PID)." | tee -a "$LOGFILE"

echo ""
echo "Fix devcontainer helper finished: $(date)" | tee -a "$LOGFILE"
echo ""
echo "=========================================="
echo "✅ Devcontainer fixes applied!"
echo "=========================================="
echo ""
echo "Next steps:"
echo "  1. Reload your terminal to get the /Codempose prompt"
echo "  2. Go to PORTS tab and make port 8888 Public"
echo "  3. Click the globe icon 🌐 to open browser"
echo "  4. View your outputs at /first.pdf"
echo ""
echo "HTTP Server: http://localhost:8888"
echo "PID: $NEW_PID"
echo "Logs: $LOGFILE"
echo ""
