"""Second study file (clean generated).

Builds a two-stave composition: a 16-note melody composed of four
4-note phrases. Harmony is generated by chordifying the full melody.
Returns canonical `score_data` (metadata + parts) for direct engraving.
"""

import _study_path  # Auto-path setup for study files
from __future__ import annotations

"""Definitive `second.py` template — snippet-first composition example.

This file follows the project's contract:
- SOURCE_THEME_LILY is the single source-of-truth (LilyPond \relative snippet).
- We parse that snippet with `lilypond_parser.parse_lilypond_to_data`.
- Transformations operate on music21 Parts produced from the parser.
- The primary builder returns canonical `score_data` (metadata + parts).

This module is importable and safe: it does not run the engraving pipeline
when executed as a script. The __main__ block only prints a short summary.
"""

from typing import Dict, List
from lilypond_parser import parse_lilypond_to_data
from music_data import extract_data_from_part, data_to_part
from transformations import (
    identity,
    transpose_part,
    invert_part,
    retrograde_part
)


# ---------------------------------------------------------------------------
# 1) Snippet as the Source of Truth
# ---------------------------------------------------------------------------
# The primary musical idea: handwritten LilyPond \relative snippet.
# Edit this string to change the seed theme for all programmatic transforms.
SOURCE_THEME_LILY = r"\relative c' { \time 4/4 \key c \major e4 b4 e'4 b4 }"
SOURCE_MELODY_LILY = r"\relative e { \time 6/4 \key c \major \tempo 4=90 e2 bmol4 c2 r4 | e2 f#4 e2 r4 | b2. f'2. | e2. c2. | e2 b2 c2 }"


# ---------------------------------------------------------------------------
# 2) Composition builder (chains transformations)
# ---------------------------------------------------------------------------
def build_score_data() -> Dict[str, Dict]:
    """Build a multi-part score_data dictionary from SOURCE_THEME_LILY.

    Workflow:
    1. Parse SOURCE_THEME_LILY with parse_lilypond_to_data -> canonical events.
    2. Reconstruct a music21.Part via data_to_part so we can use music21 transforms.
    3. Build phrases by applying reusable transforms (imported from transformations.py).
    4. Concatenate canonical event lists to form final parts.
    5. Return {'metadata': {...}, 'parts': {'Melody': [...], 'Harmony': [...]}}
    """
    # Parse the source snippet into canonical score_data
    parsed = parse_lilypond_to_data(SOURCE_THEME_LILY, part_name='Theme')
    metadata = parsed.get('metadata', {})
    theme_events = parsed.get('parts', {}).get('Theme', [])

    # Reconstruct a music21.Part from the parsed events (safe to transform)
    theme_part = data_to_part(theme_events, metadata)
    theme_part.id = 'Theme'

    # Build phrases by applying transformations to the parsed theme
    phrase1 = identity(theme_part)
    phrase2 = transpose_part(theme_part, 'P5')
    phrase3 = invert_part(theme_part, 'G4')
    phrase4 = retrograde_part(phrase2)

    # Convert each phrase back to canonical event lists
    ev1 = extract_data_from_part(phrase1)
    ev2 = extract_data_from_part(phrase2)
    ev3 = extract_data_from_part(phrase3)
    ev4 = extract_data_from_part(phrase4)

    # Concatenate to form the full melody events (snippet-first concatenation)
    melody_events: List[dict] = []
    for ev in (ev1, ev2, ev3, ev4):
        melody_events.extend(ev)

    # Build harmony by reconstructing a Part from the melody events and chordifying
    full_melody_part = data_to_part(melody_events, metadata)
    full_melody_part.id = 'Melody'
    harmony_part = full_melody_part.chordify()
    harmony_events = extract_data_from_part(harmony_part)

    # Compose final score_data. Preserve original metadata but allow the
    # composer to override title for this particular study.
    out_meta = dict(metadata) if metadata else {}
    out_meta.setdefault('title', 'Second Study (Snippet-first)')

    score_data = {
        'metadata': out_meta,
        'parts': {
            'Melody': melody_events,
            'Harmony': harmony_events,
        },
    }
    return score_data


# Expose a small public API for tooling and tests
__all__ = ['SOURCE_THEME_LILY', 'build_score_data', 'transpose_part', 'invert_part', 'retrograde_part']


# Self-executing entry point - enables direct execution with: python second.py
if __name__ == '__main__':
    from project_template import run_pipeline_from_file
    run_pipeline_from_file(__file__)


