"""
TWELFTH STUDY: All Transformations on a Single Line
====================================================

This study demonstrates the complete four-station workflow with all relevant
music21 transformations applied to a single melodic snippet.

Four-Station Workflow:
1. Station 1 (LilyPond): Original snippet - the source of truth
2. Station 2 (TinyNotation): Auto-generated equivalent representation
3. Station 3 (Shorthand): Arrange voices using declarative shorthand notation
4. Station 4 (Programmatic): Apply all transformations and document them

Structure:
- Identity (original snippet)
- Intermezzo (harmony - recurring between transformations)
- All transformations (transpose, invert, retrograde, augment, diminish, octave shifts)

PROMOTION TOGGLES:
- PROMOTE_TO_TINYNOTATION: When True, TinyNotation becomes the dominant format
- PROMOTE_TO_PROGRAMMATIC: When True, programmatic code dominates over shorthand
"""

import _study_path  # Auto-path setup for study files

# ============================================================================
# PROMOTION TOGGLES
# ============================================================================

PROMOTE_TO_TINYNOTATION = False
PROMOTE_TO_PROGRAMMATIC = False


# ============================================================================
# IMPORTS
# ============================================================================

from typing import Dict, List
import copy
import music21

from lilypond_parser import parse_lilypond_to_data
from music_data import extract_data_from_part, data_to_part
from voice_documentation import register_and_document_voice
from composition_shorthand import (
    build_score_from_assignments,
    transpose_events,
    invert_events
)
# Import transformation functions from centralized module
from transformations import (
    identity,
    transpose_part,
    invert_part,
    retrograde_part,
    augment_part,
    diminish_part,
    chordify_part
)


# ============================================================================
# STATION 1: ORIGINAL LILYPOND SNIPPET
# ============================================================================

# The single source of truth - our melodic snippet (no accidentals for clarity)
# Expected: First e2 should be E4 (not E3, not E5)
# No manual octave markers needed - relative octave logic handles everything!
SOURCE_MELODY_LILY = r"\relative e { \time 6/4 \key c \major \tempo 4=90 e2 b4 c2 r4 | e2 f4 e2 r4 | b2. f2. | e2. c2. | e2 b2 c2 }"


# ============================================================================
# STATION 2: TINYNOTATION EQUIVALENT
# ============================================================================

# Auto-generated by the parser - will be populated during build
SOURCE_MELODY_TINY = "tinynotation: 6/4 e2 b,4 c2 r4 e2 f4 e2 r4 b,2. f2. e2. c2. e2 b,2 c2"


# ============================================================================
# STATION 3: SHORTHAND STRUCTURE
# ============================================================================

# Declarative arrangement: Identity + Intermezzo + All Transformations
# Each transformation is separated by the INTERMEZZO harmony
VOICE_ASSIGNMENTS = {
    'SingleLine': {
        # Identity (original snippet)
        'Original': 'SNIPPET',
        
        # Intermezzo (harmony - chordified snippet)
        'Intermezzo_1': 'HARMONY',
        
        # Transformation 1: Transposed up P5
        'Transposed_P5': 'SNIPPET_TRANSPOSED_P5',
        
        # Intermezzo (recurring)
        'Intermezzo_2': 'HARMONY',
        
        # Transformation 2: Inverted around C4
        'Inverted_C4': 'SNIPPET_INVERTED_C4',
        
        # Intermezzo (recurring)
        'Intermezzo_3': 'HARMONY',
        
        # Transformation 3: Retrograde
        'Retrograde': 'SNIPPET_RETROGRADE',
        
        # Intermezzo (recurring)
        'Intermezzo_4': 'HARMONY',
        
        # Transformation 4: Augmented (x2 duration)
        'Augmented_x2': 'SNIPPET_AUGMENTED',
        
        # Intermezzo (recurring)
        'Intermezzo_5': 'HARMONY',
        
        # Transformation 5: Diminished (x0.5 duration)
        'Diminished_x0.5': 'SNIPPET_DIMINISHED',
        
        # Intermezzo (recurring)
        'Intermezzo_6': 'HARMONY',
        
        # Transformation 6: Octave up
        'Octave_Up': 'SNIPPET_OCTAVE_UP',
        
        # Intermezzo (recurring)
        'Intermezzo_7': 'HARMONY',
        
        # Transformation 7: Octave down
        'Octave_Down': 'SNIPPET_OCTAVE_DOWN',
    }
}


# ============================================================================
# STATION 4: PROGRAMMATIC GENERATION WITH DOCUMENTATION
# ============================================================================

# Note: All transformation functions are now imported from transformations.py
# This includes: identity, transpose_part, invert_part, retrograde_part,
# augment_part, diminish_part, and chordify_part


def build_score_data() -> Dict[str, Dict]:
    """
    Build complete transformation showcase - programmatic version.
    
    This bypasses shorthand and builds everything manually to ensure it works.
    """
    print("\n" + "="*70)
    print("TWELFTH STUDY: All Transformations (Programmatic)")
    print("="*70)
    
    # Parse original snippet
    parsed = parse_lilypond_to_data(SOURCE_MELODY_LILY, part_name='Melody')
    snippet_events = parsed.get('parts', {}).get('Melody', [])
    snippet_part = data_to_part(snippet_events, parsed.get('metadata', {}))
    
    print(f"\n✓ Parsed snippet: {len(snippet_events)} events")
    print("\nFirst 10 events:")
    for i, event in enumerate(snippet_events[:10]):
        if event.get('type') == 'note':
            step = event['step']
            octave = event['octave']
            ql = event['ql']
            orig = event.get('original_token', '?')
            print(f"  {i+1:2d}. {orig:8s} → {step}{octave} (ql={ql})")
        else:
            print(f"  {i+1:2d}. REST (ql={event['ql']})")
    
    # Generate transformations
    print("\n[Generating transformations...]")
    harmony = extract_data_from_part(chordify_part(snippet_part))
    transposed = extract_data_from_part(transpose_part(snippet_part, 'P5'))
    inverted = extract_data_from_part(invert_part(snippet_part, 'C4'))
    retrograde = extract_data_from_part(retrograde_part(snippet_part))
    augmented = extract_data_from_part(augment_part(snippet_part, 2.0))
    diminished = extract_data_from_part(diminish_part(snippet_part, 2.0))
    octave_up = extract_data_from_part(transpose_part(snippet_part, 'P8'))
    octave_down = extract_data_from_part(transpose_part(snippet_part, '-P8'))
    
    # Helper to create a bar line marker
    def bar_line(style="||"):
        """Create a bar line event marker."""
        return {'type': 'barline', 'style': style, 'ql': 0.0}
    
    # Manual assembly: Identity + [Intermezzo + Transformation] × 7
    # Use double bar lines to mark transitions
    single_line = []
    
    # Section 1: Original
    single_line.extend(snippet_events)
    single_line.append(bar_line("||"))
    
    # Section 2: Harmony Intermezzo 1
    single_line.extend(harmony)
    single_line.append(bar_line("||"))
    
    # Section 3: Transposed P5
    single_line.extend(transposed)
    single_line.append(bar_line("||"))
    
    # Section 4: Harmony Intermezzo 2
    single_line.extend(harmony)
    single_line.append(bar_line("||"))
    
    # Section 5: Inverted around C4
    single_line.extend(inverted)
    single_line.append(bar_line("||"))
    
    # Section 6: Harmony Intermezzo 3
    single_line.extend(harmony)
    single_line.append(bar_line("||"))
    
    # Section 7: Retrograde
    single_line.extend(retrograde)
    single_line.append(bar_line("||"))
    
    # Section 8: Harmony Intermezzo 4
    single_line.extend(harmony)
    single_line.append(bar_line("||"))
    
    # Section 9: Augmented (x2)
    single_line.extend(augmented)
    single_line.append(bar_line("||"))
    
    # Section 10: Harmony Intermezzo 5
    single_line.extend(harmony)
    single_line.append(bar_line("||"))
    
    # Section 11: Diminished (x0.5)
    single_line.extend(diminished)
    single_line.append(bar_line("||"))
    
    # Section 12: Harmony Intermezzo 6
    single_line.extend(harmony)
    single_line.append(bar_line("||"))
    
    # Section 13: Octave Up
    single_line.extend(octave_up)
    single_line.append(bar_line("||"))
    
    # Section 14: Harmony Intermezzo 7
    single_line.extend(harmony)
    single_line.append(bar_line("||"))
    
    # Section 15: Octave Down (final)
    single_line.extend(octave_down)
    
    print(f"\n✅ Built complete score: {len(single_line)} total events")
    print("   Structure: Original + 7 × (Intermezzo + Transformation)")
    
    # Voice tracking metadata - document each section
    voice_tracking = {
        '01_Original': {
            'source': 'SOURCE_MELODY_LILY',
            'transformation': 'identity',
            'description': 'Original melodic snippet',
            'events': len(snippet_events),
        },
        '02_Harmony_1': {
            'source': 'SOURCE_MELODY_LILY',
            'transformation': 'harmonize (root + M3 + P5)',
            'description': 'Harmony intermezzo (triadic chords)',
            'events': len(harmony),
        },
        '03_Transposed_P5': {
            'source': 'SOURCE_MELODY_LILY',
            'transformation': 'transpose(P5)',
            'description': 'Transposed up by perfect fifth',
            'events': len(transposed),
        },
        '04_Harmony_2': {
            'source': 'SOURCE_MELODY_LILY',
            'transformation': 'harmonize (root + M3 + P5)',
            'description': 'Harmony intermezzo (triadic chords)',
            'events': len(harmony),
        },
        '05_Inverted_C4': {
            'source': 'SOURCE_MELODY_LILY',
            'transformation': 'invert(center=C4)',
            'description': 'Melodic inversion around C4',
            'events': len(inverted),
        },
        '06_Harmony_3': {
            'source': 'SOURCE_MELODY_LILY',
            'transformation': 'harmonize (root + M3 + P5)',
            'description': 'Harmony intermezzo (triadic chords)',
            'events': len(harmony),
        },
        '07_Retrograde': {
            'source': 'SOURCE_MELODY_LILY',
            'transformation': 'retrograde()',
            'description': 'Reversed note order',
            'events': len(retrograde),
        },
        '08_Harmony_4': {
            'source': 'SOURCE_MELODY_LILY',
            'transformation': 'harmonize (root + M3 + P5)',
            'description': 'Harmony intermezzo (triadic chords)',
            'events': len(harmony),
        },
        '09_Augmented_x2': {
            'source': 'SOURCE_MELODY_LILY',
            'transformation': 'augment(factor=2.0)',
            'description': 'Durations doubled',
            'events': len(augmented),
        },
        '10_Harmony_5': {
            'source': 'SOURCE_MELODY_LILY',
            'transformation': 'harmonize (root + M3 + P5)',
            'description': 'Harmony intermezzo (triadic chords)',
            'events': len(harmony),
        },
        '11_Diminished_x0.5': {
            'source': 'SOURCE_MELODY_LILY',
            'transformation': 'diminish(factor=2.0)',
            'description': 'Durations halved',
            'events': len(diminished),
        },
        '12_Harmony_6': {
            'source': 'SOURCE_MELODY_LILY',
            'transformation': 'harmonize (root + M3 + P5)',
            'description': 'Harmony intermezzo (triadic chords)',
            'events': len(harmony),
        },
        '13_Octave_Up': {
            'source': 'SOURCE_MELODY_LILY',
            'transformation': 'transpose(P8)',
            'description': 'Transposed up one octave',
            'events': len(octave_up),
        },
        '14_Harmony_7': {
            'source': 'SOURCE_MELODY_LILY',
            'transformation': 'harmonize (root + M3 + P5)',
            'description': 'Harmony intermezzo (triadic chords)',
            'events': len(harmony),
        },
        '15_Octave_Down': {
            'source': 'SOURCE_MELODY_LILY',
            'transformation': 'transpose(-P8)',
            'description': 'Transposed down one octave',
            'events': len(octave_down),
        },
    }
    
    return {
        'metadata': {
            'title': 'Twelfth Study: All Transformations',
            'composer': 'Codempose Framework',
            'time_signature': parsed.get('metadata', {}).get('time_signature', '6/4'),
            'original_snippets': {
                'SOURCE_MELODY': SOURCE_MELODY_LILY,
            },
            'tinynotation_snippets': {
                'SOURCE_MELODY': SOURCE_MELODY_TINY,
            },
            'voice_assignments': VOICE_ASSIGNMENTS,
            'voice_tracking': voice_tracking,
            # **INSPECTOR**: Include parser's TinyNotation for diagnostic purposes
            'tinynotation_inspector': parsed.get('metadata', {}).get('tinynotation_inspector', ''),
        },
        'parts': {
            'SingleLine': single_line,
        }
    }


# ============================================================================
# ALTERNATIVE: FULLY PROGRAMMATIC (NO SHORTHAND)
# ============================================================================

def build_score_data_programmatic():
    """
    Alternative implementation: Build entire score programmatically.
    
    This bypasses the shorthand system entirely, giving you complete
    control over every detail. Uncomment in main to use this version.
    
    Set PROMOTE_TO_PROGRAMMATIC = True to enable this version.
    """
    print("\n🔧 PROGRAMMATIC MODE: Building without shorthand")
    
    # Parse original snippet
    parsed = parse_lilypond_to_data(SOURCE_MELODY_LILY, part_name='Melody')
    snippet_events = parsed.get('parts', {}).get('Melody', [])
    snippet_part = data_to_part(snippet_events, parsed.get('metadata', {}))
    
    # Generate transformations
    harmony = extract_data_from_part(chordify_part(snippet_part))
    transposed = extract_data_from_part(transpose_part(snippet_part, 'P5'))
    inverted = extract_data_from_part(invert_part(snippet_part, 'C4'))
    retrograde = extract_data_from_part(retrograde_part(snippet_part))
    augmented = extract_data_from_part(augment_part(snippet_part, 2.0))
    diminished = extract_data_from_part(diminish_part(snippet_part, 2.0))
    octave_up = extract_data_from_part(transpose_part(snippet_part, 'P8'))
    octave_down = extract_data_from_part(transpose_part(snippet_part, '-P8'))
    
    # Manual assembly: Identity + Intermezzo + Transformations
    single_line = []
    single_line.extend(snippet_events)           # Original
    single_line.extend(harmony)                  # Intermezzo 1
    single_line.extend(transposed)               # Transformation 1
    single_line.extend(harmony)                  # Intermezzo 2
    single_line.extend(inverted)                 # Transformation 2
    single_line.extend(harmony)                  # Intermezzo 3
    single_line.extend(retrograde)               # Transformation 3
    single_line.extend(harmony)                  # Intermezzo 4
    single_line.extend(augmented)                # Transformation 4
    single_line.extend(harmony)                  # Intermezzo 5
    single_line.extend(diminished)               # Transformation 5
    single_line.extend(harmony)                  # Intermezzo 6
    single_line.extend(octave_up)                # Transformation 6
    single_line.extend(harmony)                  # Intermezzo 7
    single_line.extend(octave_down)              # Transformation 7
    
    return {
        'metadata': {
            'title': 'Twelfth Study: Programmatic Mode',
            'composer': 'Codempose Framework',
            'original_snippets': {
                'SOURCE_MELODY': SOURCE_MELODY_LILY,
            },
            'tinynotation_snippets': {
                'SOURCE_MELODY': SOURCE_MELODY_TINY,
            },
            'voice_assignments': VOICE_ASSIGNMENTS,
        },
        'parts': {
            'SingleLine': single_line,
        }
    }


# ============================================================================
# MAIN EXECUTION
# ============================================================================

if __name__ == '__main__':
    from project_template import run_pipeline_from_file
    
    # Override build_score_data if programmatic mode is enabled
    if PROMOTE_TO_PROGRAMMATIC:
        print("\n🔄 PROMOTION: Using programmatic mode")
        build_score_data = build_score_data_programmatic
    
    print("\n💡 Key Features:")
    print("  1. Four-station workflow: LilyPond → TinyNotation → Shorthand → Programmatic")
    print("  2. All transformations are DOCUMENTED and REUSABLE")
    print("  3. Shorthand arranges: Identity + [Intermezzo + Transformation] × 7")
    print("  4. Intermezzo (harmony) recurs between each transformation")
    print("  5. Everything on a single line - complete transformation showcase")
    print("  6. MusicXML export for MuseScore compatibility")
    print("\n🎼 Documentation shows both LilyPond AND TinyNotation formats!\n")
    
    # Run the standard pipeline (handles LilyPond, MusicXML, promotion)
    run_pipeline_from_file(__file__)

