#!/usr/bin/env bash
set -euo pipefail

# Devcontainer start helper:
# - run the generation step (project_template.py)
# - start a background http.server bound to 0.0.0.0:8888 if not already running
# - write logs to .devcontainer/devcontainer-start.log and PID to .devcontainer/devcontainer-server.pid

LOGFILE=".devcontainer/devcontainer-start.log"
PIDFILE=".devcontainer/devcontainer-server.pid"

mkdir -p .devcontainer
echo "Starting devcontainer start helper: $(date)" >> "$LOGFILE"

# Ensure canonical prompt is installed for the container user (so it persists)
if [ -f ".devcontainer/bash_prompt_choice" ]; then
  cp .devcontainer/bash_prompt_choice "$HOME/.bash_prompt_choice" || true
  chown $(id -u):$(id -g) "$HOME/.bash_prompt_choice" || true
  echo "Installed canonical prompt to $HOME/.bash_prompt_choice" >> "$LOGFILE"

  # Ensure the user's ~/.bashrc will source the prompt choice so the
  # override persists across container rebuilds and restarts. This is
  # idempotent: only append if a reference to .bash_prompt_choice is
  # not already present.
  PROMPT_GREP='bash_prompt_choice'
  if [ -f "$HOME/.bashrc" ]; then
    if ! grep -Fq "$PROMPT_GREP" "$HOME/.bashrc" 2>/dev/null; then
      printf "\n# Source project canonical prompt (installed by devcontainer)\nif [ -f \"$HOME/.bash_prompt_choice\" ]; then\n  . \"$HOME/.bash_prompt_choice\"\nfi\n" >> "$HOME/.bashrc" || true
      chown $(id -u):$(id -g) "$HOME/.bashrc" || true
      echo "Appended sourcing of $HOME/.bash_prompt_choice to $HOME/.bashrc" >> "$LOGFILE"
    else
      echo "~/.bashrc already sources bash_prompt_choice; skipping append" >> "$LOGFILE"
    fi
  else
    # If no ~/.bashrc exists, create a simple one that sources the prompt
    printf "# ~/.bashrc generated by devcontainer-start helper\nif [ -f \"$HOME/.bash_prompt_choice\" ]; then\n  . \"$HOME/.bash_prompt_choice\"\nfi\n" > "$HOME/.bashrc" || true
    chown $(id -u):$(id -g) "$HOME/.bashrc" || true
    echo "Created $HOME/.bashrc and added prompt sourcing" >> "$LOGFILE"
  fi
fi

echo "Generating score (project_template.py) ..." | tee -a "$LOGFILE"
if python3 project_template.py >> "$LOGFILE" 2>&1; then
  echo "Generation completed successfully." | tee -a "$LOGFILE"
else
  echo "Generation failed; see $LOGFILE for details. Continuing to server start." | tee -a "$LOGFILE"
fi

# Check if a server is already listening on 8888
# Ensure outputs directory exists (we want to serve generated artifacts)
mkdir -p outputs

# If a server is listening on 8888, attempt a graceful restart so it serves outputs/
if ss -ltnp 2>/dev/null | grep -q ":8888"; then
  echo "HTTP server already running on port 8888; attempting restart to serve outputs/..." | tee -a "$LOGFILE"
  if [ -f "$PIDFILE" ]; then
    OLDPID=$(cat "$PIDFILE" 2>/dev/null || true)
    if [ -n "$OLDPID" ] && ps -p "$OLDPID" > /dev/null 2>&1; then
      echo "Stopping previous server (PID $OLDPID) ..." | tee -a "$LOGFILE"
      kill "$OLDPID" || true
      sleep 0.5
    fi
  fi
fi

echo "Starting HTTP server on 0.0.0.0:8888 (serving outputs/) ..." | tee -a "$LOGFILE"
# Start server in background and record PID; serve the outputs/ directory directly
nohup python3 -m http.server 8888 --bind 0.0.0.0 --directory outputs >> "$LOGFILE" 2>&1 &
echo $! > "$PIDFILE"
echo "HTTP server started (PID $(cat $PIDFILE))." | tee -a "$LOGFILE"

echo "Devcontainer start helper finished: $(date)" >> "$LOGFILE"

exit 0
