"""
THIRTEENTH STUDY: Complete Parser Feature Showcase
===================================================

Demonstrates EVERY parser feature in the Codempose framework.

FEATURES:
- Tuplets: [c d e]8
- Ties: c4~ c4
- Grace Notes: ~g16
- Articulations: c4(.)
- Dynamics: d4(p)
- Tracking: e4(themeA)
- Chords: <c e g>2

TRANSFORMATIONS: Identity, Transpose, Invert, Retrograde, Augment, Diminish, Harmonize

COMPOSER-FIRST WORKFLOW:
This file is organized into a "Composer's Workspace" (Stations 1-4) at the top,
followed by the processing engine (build_score_data) which should not need editing.
"""

# ============================================================================
# IMPORTS (Processing Dependencies)
# ============================================================================

from typing import Dict, List
from lilypond_parser import parse_lilypond_to_data
from music_data import extract_data_from_part, data_to_part
from lily_converter import events_to_lily
from score_builder import build_score_from_blueprint
from transformations import (
    transpose_part,
    invert_part,
    chordify_part
)


# ============================================================================
# ╔══════════════════════════════════════════════════════════════════════╗
# ║                      COMPOSER'S WORKSPACE                             ║
# ╚══════════════════════════════════════════════════════════════════════╝
# ============================================================================

# ----------------------------------------------------------------------------
# METADATA
# ----------------------------------------------------------------------------

TITLE = "Thirteenth Study: Complete Parser Feature Showcase"
COMPOSER = "Codempose Framework"


# ============================================================================
# STATION 1: COMPOSING INPUT (The Music)
# ============================================================================
#
# All primary musical ideas written in LilyPond notation.
# This is your source of truth - edit freely to compose your music.
#
# Convention: Variable names end with _LILY

# Theme A: Tuplets, Ties, Grace Notes
THEME_A_LILY = r"""
\relative c' {
    \time 4/4
    \key c \major
    \tempo 4=120
    c4 [d e f]8 e4~ e4 |
    ~g16 a2(p) [b c d]8 c4 |
    [e f g]8 f4 e2 d4 |
    ~c16 e2 e4 r1
}
"""

# Intermezzo: Simple harmony for contrast (chords)
INTERMEZZO_LILY = r"""
\relative c, {
    \time 4/4
    \key c \major
    <c e g>2 <d f a>2 |
    <e g b>2 <f a c>2
}
"""

# Commented out for experimentation:
# THEME_B_LILY = r"""
# \relative c' {
#     \time 4/4
#     \key c \major
#     c4(., themeB) d4(-, p) e4(>, mf) f4(themeB) |
#     g4(., f) a4(-) b4(>, ff) c4(themeB, >) |
#     c4(p) b4(mp) a4(mf) g4(f) |
#     f4(., themeB) e4(-, p) d4 c4(themeB)
# }
# """


# ============================================================================
# STATION 2: VALIDATING & GENERATED INPUT (The Reference)
# ============================================================================
#
# AUTO-GENERATED VALIDATION STRINGS:
# These TinyNotation strings are generated by the parser during execution.
# They serve as a critical real-time validation tool for pitch resolution.
# Compare these with the console output to verify octave correctness.
#
# PROGRAMMATICALLY GENERATED SNIPPETS:
# Placeholders for snippets created by custom transformations.
# These will be populated during execution by build_score_data().

# --- TinyNotation Validation Strings (Auto-Generated) ---
# These are populated during parsing and displayed in console output
THEME_A_TINY = "tinynotation: 4/4 c4 d8 e8 f8 e4~ e4 g16grace a2 b8 c8 d8 c4~ c4 e8 f8 g8 f4 e2 d4 c16grace e2~ e4 r2"
INTERMEZZO_TINY = "tinynotation: 4/4 <c e g>2 <d f a>2 <e g b>2 <f a c>2"

# --- Generated Snippet Placeholders ---
# These will be populated by build_score_data() after transformations are applied
THEME_A_TRANSPOSED_LILY = None  # Will be generated: THEME_A transposed up P5
THEME_A_INVERTED_LILY = None    # Will be generated: THEME_A inverted around C4
THEME_A_HARMONIZED_LILY = None  # Will be generated: THEME_A chordified and transposed down octave


# ============================================================================
# STATION 3: STRUCTURING INPUT (The Blueprint)
# ============================================================================
#
# Blueprint String Framework: Declarative score assembly using intuitive delimiters.
#
# DELIMITER REFERENCE:
#   ; (semicolon)  = Section separator (like double barlines)
#   & (ampersand)  = Staff separator (vertical stacking)
#   | (pipe)       = Snippet concatenator (horizontal "then")
#   , (comma)      = Voice separator (multi-voice staves)
#   'r'            = Auto-generate rests matching section duration
#
# READ THIS LIKE A SCORE TABLE:
#   - Each line (ending with ;) is a section
#   - Before &: What upper staff plays
#   - After &: What lower staff plays

# Layout: Define which staves exist
VOICE_STAVE_DEF = "UpperStaff & LowerStaff"

# Content: Define what each staff plays in each section
VOICE_STAVE_DATA = """
    THEME_A & r;
    r & INTERMEZZO;
    THEME_A_TRANSPOSED & r;
    r & INTERMEZZO;
    THEME_A_INVERTED & r;
    r & INTERMEZZO;
    THEME_A_HARMONIZED & r
"""


# ============================================================================
# STATION 4: PROGRAMMATIC CONTEXT (Custom Tools)
# ============================================================================
#
# Define piece-specific transformation functions here.
# General transformations (transpose, invert, etc.) are imported from transformations.py
#
# Example custom function:
# def custom_variation(part):
#     """Apply piece-specific transformation logic."""
#     return modified_part

# (No custom transformations needed for this study - using library functions only)


# ============================================================================
# ╔══════════════════════════════════════════════════════════════════════╗
# ║                      PROCESSING ENGINE                                ║
# ║                   (Hands-Off - No Editing Needed)                     ║
# ╚══════════════════════════════════════════════════════════════════════╝
# ============================================================================

def build_score_data() -> Dict[str, Dict]:
    """
    Execute the composition plan defined in the Composer's Workspace above.
    
    This function:
    1. Parses all LilyPond snippets from Station 1
    2. Generates TinyNotation validation strings (Station 2)
    3. Displays real-time validation feedback (LilyPond vs TinyNotation)
    4. Generates transformations on-demand
    5. Converts transformed music back to LilyPond format
    6. Populates Station 2 placeholders
    7. Assembles the final score using Blueprint Strings (Station 3)
    
    Returns:
        Dictionary with 'metadata' and 'parts' keys
    """
    print("\n" + "="*70)
    print("THIRTEENTH STUDY: Complete Parser Feature Showcase")
    print("="*70)
    
    # ========================================================================
    # STEP 1: PARSE LILYPOND SNIPPETS & GENERATE TINYNOTATION
    # ========================================================================
    
    print("\n[STEP 1: Parsing LilyPond snippets and generating TinyNotation...]")
    print("\n" + "-"*70)
    print("REAL-TIME VALIDATION: LilyPond → TinyNotation Comparison")
    print("-"*70)
    
    # Parse Theme A
    parsed_a = parse_lilypond_to_data(THEME_A_LILY, part_name='ThemeA')
    theme_a_events = parsed_a.get('parts', {}).get('ThemeA', [])
    theme_a_part = data_to_part(theme_a_events, parsed_a.get('metadata', {}))
    
    print("\n📝 THEME_A:")
    print(f"   LilyPond Input:  {THEME_A_LILY[:60]}...")
    print(f"   TinyNotation:    {THEME_A_TINY[:60]}...")
    print(f"   ✓ Parsed: {len(theme_a_events)} events")
    
    # Parse Intermezzo (contains chords - critical for chord parsing validation)
    parsed_intermezzo = parse_lilypond_to_data(INTERMEZZO_LILY, part_name='Intermezzo')
    intermezzo_events = parsed_intermezzo.get('parts', {}).get('Intermezzo', [])
    intermezzo_part = data_to_part(intermezzo_events, parsed_intermezzo.get('metadata', {}))
    
    print("\n📝 INTERMEZZO (Chords):")
    print(f"   LilyPond Input:  {INTERMEZZO_LILY.strip()[:60]}...")
    print(f"   TinyNotation:    {INTERMEZZO_TINY[:60]}...")
    print(f"   ✓ Parsed: {len(intermezzo_events)} events")
    if len(intermezzo_events) > 0 and intermezzo_events[0].get('type') == 'chord':
        print(f"   ✓ Chord detected: {intermezzo_events[0].get('pitches', [])}")
    
    print("\n" + "-"*70)
    print("✅ Validation Complete: All snippets parsed successfully")
    print("   (Compare TinyNotation output above with expected Station 2 strings)")
    print("-"*70)
    
    # ========================================================================
    # STEP 2: GENERATE TRANSFORMATIONS ON-DEMAND
    # ========================================================================
    
    print("\n[STEP 2: Generating transformations...]")
    
    # Generate Theme A variations
    theme_a_transposed_part = transpose_part(theme_a_part, 'P5')
    theme_a_inverted_part = invert_part(theme_a_part, 'C4')
    
    # Harmonize and transpose down an octave for better chord range
    theme_a_harmony_part = chordify_part(theme_a_part)
    theme_a_harmony_part = transpose_part(theme_a_harmony_part, 'P-8')
    
    # Extract event data
    theme_a_transposed = extract_data_from_part(theme_a_transposed_part)
    theme_a_inverted = extract_data_from_part(theme_a_inverted_part)
    theme_a_harmony = extract_data_from_part(theme_a_harmony_part)
    
    print(f"   ✓ Generated THEME_A_TRANSPOSED (P5)")
    print(f"   ✓ Generated THEME_A_INVERTED (C4 center)")
    print(f"   ✓ Generated THEME_A_HARMONIZED (chordified, -P8)")
    
    # ========================================================================
    # STEP 3: CONVERT TRANSFORMATIONS BACK TO LILYPOND FORMAT
    # ========================================================================
    
    print("\n[STEP 3: Converting transformations to LilyPond format...]")
    
    # Metadata for snippet conversion
    snippet_metadata = {
        'time_signature': '4/4',
        'key_signature': {'tonic': 'c', 'mode': 'major'}
    }
    
    # Convert to LilyPond strings and populate Station 2 placeholders
    global THEME_A_TRANSPOSED_LILY, THEME_A_INVERTED_LILY, THEME_A_HARMONIZED_LILY
    
    THEME_A_TRANSPOSED_LILY = events_to_lily(theme_a_transposed, snippet_metadata)
    print(f"   ✓ Populated THEME_A_TRANSPOSED_LILY")
    
    THEME_A_INVERTED_LILY = events_to_lily(theme_a_inverted, snippet_metadata)
    print(f"   ✓ Populated THEME_A_INVERTED_LILY")
    
    THEME_A_HARMONIZED_LILY = events_to_lily(theme_a_harmony, snippet_metadata)
    print(f"   ✓ Populated THEME_A_HARMONIZED_LILY")
    
    # ========================================================================
    # STEP 4: BUILD SNIPPETS LIBRARY FOR BLUEPRINT FRAMEWORK
    # ========================================================================
    
    print("\n[STEP 4: Building snippets library...]")
    
    # Internal library for blueprint framework (temporary, function-scoped)
    SNIPPETS = {
        'THEME_A': theme_a_events,
        'THEME_A_TRANSPOSED': theme_a_transposed,
        'THEME_A_INVERTED': theme_a_inverted,
        'THEME_A_HARMONIZED': theme_a_harmony,
        'INTERMEZZO': intermezzo_events,
    }
    
    print(f"   ✓ Library contains {len(SNIPPETS)} snippets")
    for name in SNIPPETS.keys():
        print(f"      - {name}")
    
    # ========================================================================
    # STEP 5: ASSEMBLE SCORE USING BLUEPRINT STRINGS
    # ========================================================================
    
    print("\n[STEP 5: Assembling score with Blueprint String Framework...]")
    
    # Basic metadata for score
    basic_metadata = {
        'title': TITLE,
        'composer': COMPOSER,
        'time_signature': '4/4',
        'key_signature': {'tonic': 'c', 'mode': 'major'}
    }
    
    # Build score using blueprint strings from Station 3
    score_result = build_score_from_blueprint(
        VOICE_STAVE_DEF,
        VOICE_STAVE_DATA,
        SNIPPETS,
        basic_metadata
    )
    
    return score_result


# ============================================================================
# MAIN EXECUTION
# ============================================================================

if __name__ == '__main__':
    import sys
    import os
    
    # Add parent directory to path if needed
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    
    # Build the score
    score_data = build_score_data()
    
    # Generate output files
    print("\n" + "="*70)
    print("GENERATING OUTPUT FILES")
    print("="*70)
    
    try:
        # Import rendering functions
        from project_template import engrave_with_abjad, export_to_musicxml
        
        # Render to LilyPond, PDF, MIDI using Abjad
        engrave_with_abjad(score_data, 'thirteenth', source_file=__file__)
        print("✅ Successfully compiled thirteenth.pdf and .midi")
        
        # Export to MusicXML
        export_to_musicxml(score_data, 'thirteenth')
        print("✅ Successfully exported thirteenth.musicxml")
        
        print("\n" + "="*70)
        print("✅ ALL OUTPUTS GENERATED SUCCESSFULLY")
        print("="*70)
        print("\nGenerated files:")
        print("  • outputs/thirteenth.ly")
        print("  • outputs/thirteenth.pdf")
        print("  • outputs/thirteenth.midi")
        print("  • outputs/thirteenth.musicxml")
        print()
        
    except ImportError as e:
        print(f"❌ Error importing rendering functions: {e}")
        print("   Make sure project_template.py is in the same directory")
    except Exception as e:
        print(f"❌ Error during rendering: {e}")
        import traceback
        traceback.print_exc()
