"""
STATION 2 LIBRARY: 100th.py
Generated by Codempose. Copy variables back to Station 1 to reuse.
"""

# Origin: THEME_A
THEME_A = r"""d'''4-.\p fis'''8 g'''8 a'''4~ | a'''4 g'''4-> fis'''4 | e'''4. d'''8~ d'''4 | b'''4\f c''''4 d''''4"""

# Origin: BASS_FIGURE
BASS_FIGURE = r"""g4 d'4 b4 | c'2 b4 | a4 g4 fis4 | g1"""

# Origin: THEME_B
THEME_B = r"""g'4 fis'4 e'4 | d'1~ | d'4 e'4 fis'4 | g'1"""

# Origin: transpose_part(THEME_A, 'P4')
TRANSPOSE_PART_THEME_A___P4__ = r"""g'''4 b'''8 c''''8 d''''4 | d''''4 c''''4 b'''4 | a'''4. g'''8 g'''4 | e''''4 f''''4 g''''4"""
