"""
STATION 2 LIBRARY: newfugue.py
Generated by Codempose. Copy variables back to Station 1 to reuse.
"""

# Origin: FUGUE_SUBJECT
FUGUE_SUBJECT = r"""c''4 e''4 g''8 f''8 e''8 d''8 | c''4 d''4 e''2 | f''4 e''4 d''4 c''4 | b'2 c''2"""

# Origin: transpose_part(FUGUE_SUBJECT, 'P5')
TRANSPOSE_PART_FUGUE_SUBJECT___P5__ = r"""g''4 b''4 d'''8 c'''8 b''8 a''8 | g''4 a''4 b''2 | c'''4 b''4 a''4 g''4 | fis''2 g''2"""
